version: 0.2

env:
  variables:
    APP_NAME: "hello-world-angular"
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # Install the Angular CLI
      - echo "----- Install Angular CLI -----"
      - npm install -g @angular/cli
      # Install project dependencies
      - echo "----- Install npm -----"
      - npm install
  pre_build:
      commands:
      - echo "----- Nothing to pre_build -----"
  build:
    # on-failure: ABORT
    commands:
      # Build the project
      - echo "----- Build $APP_NAME app -----"
      - ng build
      # Run headless Chrome tests
      # - echo "----- Test $APP_NAME app -----"
      # - ng test
  post_build:
    commands:
      - echo "----- Uplload to S3 $APP_NAME bucket -----"
      - cd dist/ecf-hello-world-angular
      - ls -la
      - aws s3 sync . s3://${BUCKET_NAME} --delete
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist/ecf-hello-world-angular*'