version: 0.2

env:
  variables:
    APP_NAME: "hello-world-angular"
phases:
  install:
    runtime-versions:
      nodejs: latest # Spécifie la version de nodejs à utiliser
    commands:
      - npm install -g @angular/cli #Installe Angular CLI
      - npm i -D puppeteer # Installe Puppeteer pour les tests e2e
      - npm i @angular-devkit/build-angular # Installe les dépendances pour les tests e2e
      - echo "Missing Libs" || ldd ./node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome | grep not # Affiche les librairies manquantes
      - apt-get update # Met à jour l'index des paquets
      - apt-get upgrade # Met à jour les paquets
      # Install apt-transport-https
      - apt-get install -y apt-transport-https

      # Use apt to install the Chrome dependencies
      - apt-get install -y libxcursor1
      - apt-get install -y libgtk-3-dev
      - apt-get install -y libxss1
      - apt-get install -y libasound2
      - apt-get install -y libnspr4
      - apt-get install -y libnss3
      - apt-get install -y libx11-xcb1

      # Print out missing libs
      - echo "Missing Libs" || ldd ./node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome | grep not

      - npm ci #Installe les dépendances du projet
  
  pre_build:
    commands:
      - echo "Nothing to pre_build"

  build:
    # on-failure: ABORT
    commands:
      - printenv # Affiche les variables d'environnement
      - ng build # Build le projet Angular
      # Run headless Chrome tests
      - ng test --watch=false
      - printenv
  post_build:
    commands:
      - echo "----- Uplload to S3 $APP_NAME bucket -----"
      - cd dist/ecf-hello-world-angular # Se déplace dans le dossier de build
      - ls -la
      - aws s3 sync . s3://${BUCKET_NAME} --delete # Upload le contenu du dossier de build dans le bucket S3
artifacts:
  files:
    - '**/*' # Upload tous les fichiers du dossier de build
  discard-paths: yes # Ne pas uploader le chemin du dossier de build
  base-directory: 'dist/ecf-hello-world-angular*' # Spécifie le dossier de build